In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("googleplaystore.csv")
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [6]:
df.columns[df.isna().any()]

Index(['Rating', 'Type', 'Content Rating', 'Current Ver', 'Android Ver'], dtype='object')

In [7]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [10]:
df = df.drop(df.index[10472])
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [18]:
df = df.drop(["App", "Last Updated", "Current Ver", "Android Ver"], axis=1, errors='ignore')
df

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres
0,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design
1,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play
2,ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design
3,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design
4,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity
...,...,...,...,...,...,...,...,...,...
10836,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education
10837,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education
10838,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical
10839,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference
10840,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle

In [19]:
df.columns[df.isna().any()]

Index(['Rating', 'Type'], dtype='object')

In [20]:
df.isnull().sum()

Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               0
dtype: int64

In [54]:
df['Rating'] = df['Rating'].fillna(df['Rating'].median())
df['Is_Successful'] = (df['Rating'] >= 4.2).astype(int)
df
df['Size'] = df['Size'].fillna(df['Size'].median())

# Check if there are any NaNs left
print("Missing values in Size:", df['Size'].isnull().sum())
df

Missing values in Size: 10839

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Is_Successful
0,0,4.1,1182,NaN,10000,0,0.0,1,9,0
1,0,3.9,5922,NaN,500000,0,0.0,1,12,0
2,0,4.7,5679,NaN,5000000,0,0.0,1,9,1
3,0,4.5,1946,NaN,50000000,0,0.0,4,9,1
4,0,4.3,5922,NaN,100000,0,0.0,1,11,1
...,...,...,...,...,...,...,...,...,...,...
10836,11,4.5,3470,NaN,5000,0,0.0,1,39,1
10837,11,5.0,3587,NaN,100,0,0.0,1,39,1
10838,20,4.3,2854,NaN,1000,0,0.0,1,71,1
10839,3,4.5,355,NaN,1000,0,0.0,3,19,1
10840,18,4.5,3578,NaN,10000000,0,0.0,1,67,1

In [30]:
df['Installs'] = df['Installs'].astype(str).str.replace('+', '', regex=False).str.replace(',', '', regex=False)
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce').fillna(0).astype(int)
df['Price'] = df['Price'].astype(str).str.replace('$', '', regex=False)
df['Price'] = pd.to_numeric(df['Price'], errors='coerce').fillna(0).astype(float)
df

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Is_Successful
0,ART_AND_DESIGN,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,0
1,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,0
2,ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,1
3,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,1
4,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,1
...,...,...,...,...,...,...,...,...,...,...
10836,FAMILY,4.5,38,53M,5000,Free,0.0,Everyone,Education,1
10837,FAMILY,5.0,4,3.6M,100,Free,0.0,Everyone,Education,1
10838,MEDICAL,4.3,3,9.5M,1000,Free,0.0,Everyone,Medical,1
10839,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000,Free,0.0,Mature 17+,Books & Reference,1
10840,LIFESTYLE,4.5,398307,19M,10000000,Free,0.0,Everyone,Lifestyle,1

In [55]:
import numpy as np
def clean_size(x):
    # Convert to string, lowercase, and remove spaces
    x = str(x).lower().strip() 
    
    if 'm' in x:
        # Extract only the numbers/decimals and convert to float
        return float(''.join(c for c in x if c.isdigit() or c == '.'))
    elif 'k' in x:
        # Extract digits, convert to float, then convert KB to MB
        val = float(''.join(c for c in x if c.isdigit() or c == '.'))
        return val / 1024
    else:
        # This catches "varies with device" or any other text
        return np.nan

df['Size'] = df['Size'].apply(clean_size)

In [38]:
fo = df.select_dtypes(include="object").columns
for i in fo:
    df[i] = df[i].fillna(df[i].mode()[0])
df

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Is_Successful
0,ART_AND_DESIGN,4.1,159,NaN,10000,Free,0.0,Everyone,Art & Design,0
1,ART_AND_DESIGN,3.9,967,NaN,500000,Free,0.0,Everyone,Art & Design;Pretend Play,0
2,ART_AND_DESIGN,4.7,87510,NaN,5000000,Free,0.0,Everyone,Art & Design,1
3,ART_AND_DESIGN,4.5,215644,NaN,50000000,Free,0.0,Teen,Art & Design,1
4,ART_AND_DESIGN,4.3,967,NaN,100000,Free,0.0,Everyone,Art & Design;Creativity,1
...,...,...,...,...,...,...,...,...,...,...
10836,FAMILY,4.5,38,NaN,5000,Free,0.0,Everyone,Education,1
10837,FAMILY,5.0,4,NaN,100,Free,0.0,Everyone,Education,1
10838,MEDICAL,4.3,3,NaN,1000,Free,0.0,Everyone,Medical,1
10839,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0.0,Mature 17+,Books & Reference,1
10840,LIFESTYLE,4.5,398307,NaN,10000000,Free,0.0,Everyone,Lifestyle,1

In [57]:
df['Size'] = df['Size'].fillna(df['Size'].median())

# Check again—this should now be 0
print("Missing values in Size:", df['Size'].isnull().sum())
df

Missing values in Size: 10839

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Is_Successful
0,0,4.1,1182,NaN,10000,0,0.0,1,9,0
1,0,3.9,5922,NaN,500000,0,0.0,1,12,0
2,0,4.7,5679,NaN,5000000,0,0.0,1,9,1
3,0,4.5,1946,NaN,50000000,0,0.0,4,9,1
4,0,4.3,5922,NaN,100000,0,0.0,1,11,1
...,...,...,...,...,...,...,...,...,...,...
10836,11,4.5,3470,NaN,5000,0,0.0,1,39,1
10837,11,5.0,3587,NaN,100,0,0.0,1,39,1
10838,20,4.3,2854,NaN,1000,0,0.0,1,71,1
10839,3,4.5,355,NaN,1000,0,0.0,3,19,1
10840,18,4.5,3578,NaN,10000000,0,0.0,1,67,1

In [42]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
for i in fo:
    df[i] = le.fit_transform(df[i])
df

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Is_Successful
0,0,4.1,1182,NaN,10000,0,0.0,1,9,0
1,0,3.9,5922,NaN,500000,0,0.0,1,12,0
2,0,4.7,5679,NaN,5000000,0,0.0,1,9,1
3,0,4.5,1946,NaN,50000000,0,0.0,4,9,1
4,0,4.3,5922,NaN,100000,0,0.0,1,11,1
...,...,...,...,...,...,...,...,...,...,...
10836,11,4.5,3470,NaN,5000,0,0.0,1,39,1
10837,11,5.0,3587,NaN,100,0,0.0,1,39,1
10838,20,4.3,2854,NaN,1000,0,0.0,1,71,1
10839,3,4.5,355,NaN,1000,0,0.0,3,19,1
10840,18,4.5,3578,NaN,10000000,0,0.0,1,67,1

In [43]:
x = df.drop(["Is_Successful", "Rating"], axis=1)
y = df["Is_Successful"]

In [59]:
df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce').fillna(0)
df

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Is_Successful
0,0,4.1,1182,NaN,10000,0,0.0,1,9,0
1,0,3.9,5922,NaN,500000,0,0.0,1,12,0
2,0,4.7,5679,NaN,5000000,0,0.0,1,9,1
3,0,4.5,1946,NaN,50000000,0,0.0,4,9,1
4,0,4.3,5922,NaN,100000,0,0.0,1,11,1
...,...,...,...,...,...,...,...,...,...,...
10836,11,4.5,3470,NaN,5000,0,0.0,1,39,1
10837,11,5.0,3587,NaN,100,0,0.0,1,39,1
10838,20,4.3,2854,NaN,1000,0,0.0,1,71,1
10839,3,4.5,355,NaN,1000,0,0.0,3,19,1
10840,18,4.5,3578,NaN,10000000,0,0.0,1,67,1

In [46]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [60]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=300, max_depth=20, random_state=42, class_weight="balanced")
model.fit(x_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=20, n_estimators=300,
                       random_state=42)

In [61]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [62]:
y_pred = model.predict(x_test)
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy Score: 0.6969557195571956

Confusion Matrix:
 [[ 346  316]
 [ 341 1165]]

Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.52      0.51       662
           1       0.79      0.77      0.78      1506

    accuracy                           0.70      2168
   macro avg       0.65      0.65      0.65      2168
weighted avg       0.70      0.70      0.70      2168